Test branch jonathan s
AdamGrubb/grupp10 pull request #44
Opened 2023-05-16 08:06 UTC by nebusoku91

Olika ändringar i CSS & Font och övriga ändringar för att förbättra användarupplevelsen.

2023-05-16 08:38 UTC, Grandelius requested changes
Vill du ändra denna i RecipePage.css så att ingredienserna anpassas till antalet ingredienser.
Tidigare var det en satt längd på den men i och med att bilden justeras tycker jag att det är bättre att ingrediens rutan inte har en fast längd. Bilden jag bifogat är så du kan ändra det till 

![Skärmbild 2023-05-16 103626](https://github.com/AdamGrubb/grupp10/assets/112860709/c2b2b4d9-551a-4bb1-88d9-624898058364)

2023-05-16 08:49 UTC, nebusoku91 commented
> Vill du ändra denna i RecipePage.css så att ingredienserna anpassas till antalet ingredienser. Tidigare var det en satt längd på den men i och med att bilden justeras tycker jag att det är bättre att ingrediens rutan inte har en fast längd. Bilden jag bifogat är så du kan ändra det till
> 
> ![Skärmbild 2023-05-16 103626](https://user-images.githubusercontent.com/112860709/238585223-c2b2b4d9-551a-4bb1-88d9-624898058364.png)

done and done

2023-05-16 08:51 UTC, Grandelius approved these changes

2023-05-16 12:59 UTC, johannesern approved these changes

2023-05-17 07:04 UTC, AdamGrubb approved these changes

2023-05-17 07:05 UTC, merged